defaults:
  - _self_
  - override hydra/job_logging: default
  - override hydra/hydra_logging: default

hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

# Image processing configurations
image_specs:
  valid_dimensions:
    - [744, 1045]  # width x height
    - [744, 1039]
    - [1500, 2100]
  valid_dpis: [72, 96]
  
# PDF output configurations
pdf_output:
  page_size: A4
  images_per_row: 3
  margin: 20  # mm
  spacing: -0.15  # mm between images

# Input/Output configurations
folders:
  input_paths:
    - ./img/finished
  supported_extensions: [".jpg", ".jpeg", ".png"]

# Logging configuration
logging:
  level: INFO
  file: ${hydra:run.dir}/process.log